import { useNavigate } from 'react-router-dom';
import { Video, Sparkles, ArrowRight, Zap, Music, Upload, Globe } from 'lucide-react';

export default function HomePage() {
    const navigate = useNavigate();

    return (
        <div className="page fade-in">
            {/* Hero Section */}
            <div className="hero">
                <div style={{ fontSize: '3rem', marginBottom: '12px' }}>🎬</div>
                <h1>
                    Welcome to <span className="gradient-text">SujathaVlogs</span> Studio
                </h1>
                <p>
                    Create stunning AI-powered videos for YouTube in minutes.
                    Generate images, add music, and upload — all automated! ✨
                </p>
            </div>

            {/* Quick Stats */}
            <div style={{ display: 'flex', gap: '12px', justifyContent: 'center', marginBottom: '30px' }} className="stagger">
                <div className="badge badge-primary">🎯 AI Powered</div>
                <div className="badge badge-accent">🌐 EN + తెలుగు</div>
                <div className="badge badge-success">⚡ Auto Upload</div>
            </div>

            {/* Action Cards */}
            <div className="action-cards stagger">
                {/* Manual Create */}
                <div
                    className="card card-glow action-card"
                    onClick={() => navigate('/create')}
                >
                    <div className="action-card-icon" style={{ background: 'rgba(255, 0, 51, 0.12)' }}>
                        <Video size={28} color="#ff0033" />
                    </div>
                    <h3>Create Video</h3>
                    <p>Enter a text prompt, generate AI images, add music, and create a video step by step.</p>
                    <div className="arrow"><ArrowRight size={20} /></div>
                </div>

                {/* Viral Auto Mode */}
                <div
                    className="card card-glow action-card"
                    onClick={() => navigate('/viral')}
                >
                    <div className="action-card-icon" style={{ background: 'rgba(139, 92, 246, 0.12)' }}>
                        <Sparkles size={28} color="#8b5cf6" />
                    </div>
                    <h3>Viral AI Studio</h3>
                    <p>One-click magic! AI finds trending topics, creates scripts, generates everything automatically.</p>
                    <div className="arrow"><ArrowRight size={20} /></div>
                </div>

                {/* My Videos */}
                <div
                    className="card card-glow action-card"
                    onClick={() => navigate('/videos')}
                >
                    <div className="action-card-icon" style={{ background: 'rgba(16, 185, 129, 0.12)' }}>
                        <Upload size={28} color="#10b981" />
                    </div>
                    <h3>My Videos</h3>
                    <p>View, download, and manage all your created videos. Ready for YouTube upload.</p>
                    <div className="arrow"><ArrowRight size={20} /></div>
                </div>
            </div>

            {/* Features */}
            <div style={{ marginTop: '40px' }}>
                <h2 style={{ textAlign: 'center', marginBottom: '20px' }}>How It Works</h2>
                <div className="action-cards stagger">
                    <div className="card" style={{ textAlign: 'center', padding: '20px' }}>
                        <div style={{ fontSize: '2rem', marginBottom: '8px' }}>✍️</div>
                        <h4 style={{ fontSize: '0.9rem' }}>1. Enter Prompt</h4>
                        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Type what you want or let AI suggest viral topics</p>
                    </div>
                    <div className="card" style={{ textAlign: 'center', padding: '20px' }}>
                        <div style={{ fontSize: '2rem', marginBottom: '8px' }}>🎨</div>
                        <h4 style={{ fontSize: '0.9rem' }}>2. AI Creates</h4>
                        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Images generated by Gemini AI with beautiful styles</p>
                    </div>
                    <div className="card" style={{ textAlign: 'center', padding: '20px' }}>
                        <div style={{ fontSize: '2rem', marginBottom: '8px' }}>🎵</div>
                        <h4 style={{ fontSize: '0.9rem' }}>3. Add Music</h4>
                        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Search Telugu folk, devotional, or upload your own track</p>
                    </div>
                    <div className="card" style={{ textAlign: 'center', padding: '20px' }}>
                        <div style={{ fontSize: '2rem', marginBottom: '8px' }}>🚀</div>
                        <h4 style={{ fontSize: '0.9rem' }}>4. Upload</h4>
                        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Download or auto-upload to YouTube with SEO tags</p>
                    </div>
                </div>
            </div>

            {/* Channel Info */}
            <div className="card" style={{ marginTop: '30px', textAlign: 'center', background: 'var(--gradient-card)' }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', marginBottom: '8px' }}>
                    <Globe size={18} color="var(--primary)" />
                    <span style={{ fontWeight: 700 }}>sujathananammavlogs</span>
                </div>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Connected YouTube Channel</p>
            </div>
        </div>
    );
}
